### ISSUE TITLE
Feature: have knowledge about the current user config

### ISSUE THREAD

**Issue by maelp** [baalimago/clai#1]
I like to use https://github.com/TheR1D/shell_gpt/ which includes some knowledge about the user context, eg whether it is using Linux, osX, etc, so the responses can be more precise, perhaps there are some inspiration to take?

**Comment by baalimago** [comment]
Hmm, for sure good stuff. I might just joink some sort of 'command mode', thanks for the tip. 

Lucky for me I didn't know of shell_gpt before your comment, otherwise I 100% wouldn't have written this tool
