### ISSUE TITLE
weird issue with the help option

### ISSUE THREAD

**Issue by perbu** [baalimago/clai#5]
When invoking with -help the term "Default is" disappears from the output.

Output when running with the built-in shell in Goland, same result with zsh:
```
~/git/perbu/clai git:[main]
go run ./... -h
Usage of /var/folders/ld/2_t606911_lbplk26p9_k3qw0000gn/T/go-build676325665/b001/exe/clai:
  -I string
        Set the string to replace with stdin.  is '{}'. (flag syntax borrowed from xargs)
  -chat-model string
        Set the chat model to use.  is gpt-4-turbo-preview. Mutually exclusive with cm flag.
  -cm string
        Set the chat model to use.  is gpt-4-turbo-preview. Mutually exclusive with chat-model flag.
  -i    Set to true to replace '{}' with stdin. This is overwritten by -I and -replace.  is false. (flag syntax borrowed from xargs)'
```

**Comment by baalimago** [comment]
Hmm, it seems to be a mass-string-replace error from one of the larger refactors.

When I looked into it I found that there's been a tankevurpa (or "tankekryss", as claude suggest it should be translated to) in the configuration system at large after the refactor, I'm working on an update to straighten things out!

**Comment by baalimago** [comment]
Ok I created a new version `v1.2.9` which has updated `clai -h`, which in turn encourages use of `clai h`. But both should be significantly improved. Also fixed the model selection, which was broken before.
